# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "xProject_demo" do
pod "NSLogger"
pod 'Underscore.m', '~> 0.2.1'
end

target "xProject_demoTests" do

end

